version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 10s
      retries: 10


  backend:
    build:
      context: ./Backend
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      rabbitmq:
        condition: service_healthy
    links: 
        - rabbitmq

  flask:
    build:
      context: ./Flask
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    depends_on:
      rabbitmq:
        condition: service_healthy
    links: 
        - rabbitmq

